# Use a imagem base do Python
FROM python:3.11-slim

# --- ADICIONE ESTAS LINHAS PARA INSTALAR O CLIENTE POSTGRES ---
# Instala psql, que é necessário para o script wait-for-it.sh
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
# -------------------------------------------------------------

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências
COPY requirements.txt .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o script de espera e dá permissão de execução
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh